<?php
session_start();
require_once('../../model/db_connection/connection.php');
require_once('../../tcpdf/tcpdf.php');

// ────────────────────────────────────────────────
// Custom TCPDF class with Header & Footer
// ────────────────────────────────────────────────
class TailoringSlipPDF extends TCPDF {
    public function Header() {
        // Logo on the left - increased size
        $image_file = 'https://admin.darjanafashion.com/assets/img/illustrations/shopping_logo.png';
        $this->Image($image_file, 15, 12, 40, 0, 'PNG', '', 'T', false, 300, '', false, false, 0, false, false, false);
        
        // Company name - perfectly centered on the page
        $this->SetFont('helvetica', 'B', 18);
        
        // Save current position
        $currentY = $this->GetY();
        
        // Calculate center position (page width/2)
        $pageWidth = $this->getPageWidth();
        $textWidth = $this->GetStringWidth('DARJANA FASHION');
        $centerX = ($pageWidth - $textWidth) / 2;
        
        // Set position to exact center
        $this->SetXY($centerX, 15);
        $this->Cell($textWidth, 10, 'DARJANA FASHION', 0, 1, 'C');
        
        // Add line under DARJANA FASHION
        $this->SetLineWidth(0.5);
        $this->SetDrawColor(120, 120, 120);
        $this->Line(15, $this->GetY(), $pageWidth - 15, $this->GetY());
        
        // Add some spacing after the line
        $this->SetY($this->GetY() + 5);
    }

    public function Footer() {
        $this->SetY(-18);
        $this->SetFont('helvetica', 'I', 8);
        $this->SetTextColor(120, 120, 120);
        $this->Cell(0, 10, 'Tailoring Slip | Generated by Darjana Fashion Tailoring System', 0, 0, 'C');
        $this->Cell(0, 10, 'Page '.$this->getAliasNumPage().'/'.$this->getAliasNbPages(), 0, 0, 'R');
    }
}

// ────────────────────────────────────────────────
class TailoringSlipGenerator {
    private $batch_id;
    private $conn;
    private $batch;
    private $items;
    private $tailoring_unit;

    public function __construct($conn) {
        $this->batch_id = isset($_GET['batch_id']) ? (int)$_GET['batch_id'] : 0;
        
        if ($this->batch_id <= 0) {
            die('Error: Invalid batch ID');
        }
        $this->conn = $conn;
        $this->fetchBatchDetails();
    }

    private function fetchBatchDetails() {
        // ── Batch + Unit ───────────────────────────────────────
        $query = "
            SELECT
                tb.*,
                tu.unit_name,
                tu.contact_person,
                tu.phone,
                tu.email,
                tu.address
            FROM tailoring_batches tb
            JOIN tailoring_units tu ON tb.tailoring_unit_id = tu.ids
            WHERE tb.batch_id = ?";
        
        $stmt = $this->conn->prepare($query);
        $stmt->bind_param('i', $this->batch_id);
        $stmt->execute();
        $result = $stmt->get_result();
        
        if ($result->num_rows === 0) {
            die('Error: Batch not found');
        }
        
        $this->batch = $result->fetch_assoc();
        
        $this->tailoring_unit = [
            'name'          => $this->batch['unit_name'],
            'contact_person'=> $this->batch['contact_person'],
            'phone'         => $this->batch['phone'],
            'email'         => $this->batch['email'],
            'address'       => $this->batch['address'],
            'description'   => $this->batch['description']
        ];

        // ── Items ──────────────────────────────────────────────
        $itemQuery = "
            SELECT
                tbi.*,
                od.order_id,
                od.product_name,
                od.quantity,
                od.product_color as color,
                od.product_size as size,
                od.product_length as length,
                od.product_notes as notes
            FROM tailoring_batch_items tbi
            JOIN order_details od ON tbi.order_detail_id = od.ids
            WHERE tbi.batch_id = ?
            ORDER BY od.order_id";
        
        $itemStmt = $this->conn->prepare($itemQuery);
        $itemStmt->bind_param('i', $this->batch_id);
        $itemStmt->execute();
        $result = $itemStmt->get_result();
        
        $this->items = [];
        while ($row = $result->fetch_assoc()) {
            $this->items[] = $row;
        }
        
        if (empty($this->items)) {
            die('Error: No items found in this batch');
        }
    }

    public function generateSlip() {
        $pdf = new TailoringSlipPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
        
        $pdf->SetCreator('Darjana Fashion');
        $pdf->SetAuthor('Darjana Fashion');
        $pdf->SetTitle('Tailoring Slip - ' . $this->batch['batch_code']);
        
        // Margins: increased top margin for larger logo
        $pdf->SetMargins(15, 40, 15); // Increased from 35 to 40
        $pdf->SetAutoPageBreak(true, 20);
        
        $pdf->AddPage();
        
        $html = $this->generateHTML();
        $pdf->writeHTML($html, true, false, true, false, '');
        
        // Output
        header('Content-Type: application/pdf');
        header('Content-Disposition: inline; filename="tailoring_slip_' . $this->batch['batch_code'] . '.pdf"');
        header('Cache-Control: private, max-age=0, must-revalidate');
        header('Pragma: public');
        
        $pdf->Output('tailoring_slip_' . $this->batch['batch_code'] . '.pdf', 'I');
        exit;
    }

    private function generateHTML() {
        $productWidth = 30;
        $lengthWidth  = 10;
    
        foreach ($this->items as $item) {
            if (strlen($item['product_name']) > 25) {
                $productWidth = 35;
                $lengthWidth  = 10;
                break;
            }
        }
    
        $html = '
        <style>
        body { font-family: DejaVu Sans, Helvetica, sans-serif; font-size: 11pt; color: #000; }
        .small { font-size: 10pt; line-height: 1.4; }
        .right { text-align: right; vertical-align: top; }
        .left { text-align: left; vertical-align: top; }
        .center { text-align: center; }
        
        .section-title {
            font-weight: bold;
            font-size: 15pt;
            padding: 8px 0;
            margin-top: 20px;
        }
        
        .info-table td { padding: 5px 0; vertical-align: top; }
        
        /* Main container with reduced border - only outer border */
        .main-container {
            border: 1px solid #ddd;  /* Lighter border */
        }
        
        /* Top row of the container - light gray bg */
        .top-row {
            background-color: #f5f5f5;  /* Lighter gray */
        }
        
        .top-row table {
            width: 100%;
        }
        
        .top-row td {
            vertical-align: top;
        }
        
        .batch-details {
            font-size: 11pt;
        }
        
        .tailoring-slip-headline {
            text-align: right;
            font-weight: bold;
            font-size: 18pt;
            color: #333;
        }
        
        /* Middle section - White background */
        .middle-row {
            background-color: #ffffff;  /* White background */
            border-top: 1px solid #ddd;  /* Very light border for separation */
        }
        
        .middle-row table {
            width: 100%;
        }
        
        .middle-row td {
            vertical-align: top;
        }
        
        .darjana-address {
            font-size: 10pt;
            line-height: 1.4;
        }
        
        .unit-details {
            text-align: right;
            font-size: 10pt;
            line-height: 1.6;
        }
        
        .unit-name {
            font-weight: bold;
            font-size: 12pt;
            margin-bottom: 5px;
        }
        
        /* Bottom section - Light gray bg */
        .bottom-description {
            background-color: #f5f5f5;  /* Same light gray as top */
            border-top: 1px solid #ddd;  /* Very light border for separation */
        }
        
        .bottom-description table {
            width: 100%;
        }
        
        .bottom-description td {
            vertical-align: top;
        }
        
        .description-content {
            font-size: 11pt;
            line-height: 1.5;
            font-style: italic;  /* Make text italic */
            font-weight: lighter;    /* Reduce text thickness (lighter weight) */
        }
        
        /* Items table - Full borders */
        .items {
            width: 100%;
            border-collapse: collapse;
            border: 1px solid #000;  /* Dark border for items table only */
            margin-top: 5px;
        }
        
        .items th, .items td {
            border: 1px solid #000;  /* Dark borders for item cells */
            padding: 8px;  /* Increased padding for better spacing */
            font-size: 10.5pt;
            word-wrap: break-word;
            line-height: 1.3;  /* Added line height for better text spacing */
        }
        
        /* Table headers - Grey background and increased height */
        .items th {
            background-color: #808080;  /* Grey color for headers */
            color: white;  /* White text for better contrast */
            font-weight: bold;
            text-align: center;
            padding: 12px 8px;  /* Increased padding for taller headers */
            font-size: 11pt;  /* Slightly larger font for headers */
            vertical-align: middle;
        }
        
        /* Regular table cells */
        .items td {
            background-color: white;
            vertical-align: middle;  /* Changed to middle for better vertical alignment */
            padding: 10px 8px;  /* More padding for data cells */
        }
        
        /* Notes row - Dynamic height based on content */
        .items tr.notes td {
            background-color: #f0f0f0;  /* Light grey background for notes */
            font-style: italic;
            font-size: 10pt;
            padding: 10px 8px;  /* More padding for notes */
            border-top: 1px solid #000;
            border-bottom: 1px solid #000;  /* Added bottom border for separation */
            vertical-align: top;
            height: auto;  /* Auto height based on content */
            min-height: 35px;  /* Increased minimum height for notes */
            white-space: normal;  /* Allow text wrapping */
            word-wrap: break-word;
            line-height: 1.4;  /* Better line spacing for notes */
        }
        
        /* Add some spacing between item groups */
        .items tr:not(.notes) td {
            border-bottom: 1px solid #000;
        }
        
        /* Remove any internal borders within sections */
        .top-row table, .middle-row table, .bottom-description table {
            border-collapse: collapse;
        }
        
        .top-row td, .middle-row td, .bottom-description td {
            border: none;  /* No borders inside sections */
        }
        </style>
    
        <!-- Single Main Container with all sections in original order -->
        <div class="main-container">
            <!-- TOP ROW: Batch details + TAILORING SLIP headline - Light gray bg -->
            <div class="top-row">
                <table width="100%">
                    <tr>
                        <td width="50%" class="batch-details" valign="top">
                            <table>
                                <tr><td width="40%"><b>Batch No</b></td><td>: '.$this->batch['batch_code'].'</td></tr>
                                <tr><td><b>Date</b></td><td>: '.date('d M Y', strtotime($this->batch['created_at'])).'</td></tr>
                            </table>
                        </td>
                        <td width="50%" valign="middle" class="tailoring-slip-headline">
                            TAILORING SLIP
                        </td>
                    </tr>
                </table>
            </div>
            
            <!-- MIDDLE ROW: Darjana Address + Tailoring Unit - White background -->
            <div class="middle-row">
                <table width="100%">
                    <tr>
                        <td width="50%" valign="top">
                            <div style="font-weight: bold; font-size: 12pt; margin-bottom: 5px;">Darjana Fashion</div>
                            <div class="darjana-address">
                                123 Fashion Street<br>
                                Garment District<br>
                                Colombo 02, Sri Lanka<br>
                                Tel: +94 11 234 5678<br>
                                Email: info@darjanafashion.com
                            </div>
                        </td>
                        <td width="50%" class="unit-details" valign="top">
                            <div class="unit-name">'.$this->tailoring_unit['name'].'</div>
                            '.$this->tailoring_unit['contact_person'].'<br>
                            '.$this->tailoring_unit['phone'].'<br>
                            '.$this->tailoring_unit['address'].'
                        </td>
                    </tr>
                </table>
            </div>
            
            <!-- BOTTOM ROW: Description Box - Light gray bg (same as top) -->
            <div class="bottom-description">
                <table width="100%">
                    <tr>
                        <td width="18%" valign="top"><b style="font-size:12pt;">Description :</b></td>
                        <td width="82%" valign="top" class="description-content">'.($this->tailoring_unit['description'] ? htmlspecialchars($this->tailoring_unit['description'], ENT_QUOTES) : 'No description available').'</td>
                    </tr>
                </table>
            </div>
        </div>
    
        <!-- ITEMS -->
        <div class="section-title">ITEMS</div>
    
        <table class="items" cellpadding="8">  <!-- Added cellpadding for additional spacing -->
            <thead>
                <tr>
                    <th width="6%" style="font-weight: bold; font-size: 10pt;">No</th>
                    <th width="24%" style="font-weight: bold; font-size: 10pt;">Order ID</th>
                    <th width="'.$productWidth.'%" style="font-weight: bold; font-size: 12pt;">Product</th>
                    <th width="8%" style="font-weight: bold; font-size: 10pt;">Qty</th>
                    <th width="12%" style="font-weight: bold; font-size: 10pt;">Color</th>
                    <th width="10%" style="font-weight: bold; font-size: 10pt;">Size</th>
                    <th width="'.$lengthWidth.'%" style="font-weight: bold; font-size: 10pt;">Length</th>
                </tr>
            </thead>
            <tbody>';
    
        foreach ($this->items as $i => $item) {
            $notes = $item['notes'] ? htmlspecialchars($item['notes'], ENT_QUOTES) : '-';
            
            // Add line breaks to notes for better formatting
            $notes = wordwrap($notes, 80, "<br>", true);
    
            $html .= '
            <tr>
                <td width="6%" class="center">'.($i+1).'</td>
                <td width="24%" class="center">#'.$item['order_id'].'</td>
                <td width="'.$productWidth.'%">'.$item['product_name'].'</td>
                <td width="8%" class="center">'.$item['quantity'].'</td>
                <td width="12%">'.$item['color'].'</td>
                <td width="10%">'.$item['size'].'</td>
                <td width="'.$lengthWidth.'%">'.$item['length'].'</td>
            </tr>
            <tr class="notes">
                <td colspan="7"><strong>Notes:</strong> '.$notes.'</td>
            </tr>';
        }
    
        $html .= '
            </tbody>
        </table>';
    
        return $html;
    }
}

// ────────────────────────────────────────────────
// Execution
// ────────────────────────────────────────────────
try {
    $connObj = new DBConnection();
    $conn = $connObj->ConnectToMYSQL();
} catch (Exception $e) {
    die('Database connection failed: ' . $e->getMessage());
}

try {
    $slip = new TailoringSlipGenerator($conn);
    $slip->generateSlip();
} catch (Exception $e) {
    die('Error generating tailoring slip: ' . $e->getMessage());
}

$conn->close();
?>